name: Build Container Image

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Get version
      run: echo "IMAGE_TAG=${GITHUB_ACTOR}" >> $GITHUB_ENV


    - name: Build Docker Image
      run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG} .

  deploy:
    name: Deploy to piku-test
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2

      - uses: rssnyder/nebula-action-step@0.1.0
        env:
          NEBULA_CA_CRT: ${{ secrets.NEBULA_CA_CRT }}
          NEBULA_NODE_CONF: ${{ secrets.NEBULA_NODE_CONF }}
          NEBULA_NODE_CRT: ${{ secrets.NEBULA_NODE_CRT }}
          NEBULA_NODE_KEY: ${{ secrets.NEBULA_NODE_KEY }}

      - uses: LuisEnMarroquin/setup-ssh-action@v1.8
        with:
          SSHKEY: ${{ secrets.PIKU_DEPLOY_KEY }}
    
      - name: Set up piku remote
        run: git remote add piku piku@192.168.100.21:mrtorrent-test
      
      - name: Push to piku
        run: git push piku